title: Ted Serbinski

permalink: /:categories/:title/

markdown: kramdown

lsi: true

kramdown:
  input: GFM

# configuration options https://github.com/ixti/jekyll-assets
assets:
  dirname: assets
  baseurl: http://d3bzjcbbiattc5.cloudfront.net/assets/
  sources:
    - _assets/js
    - _assets/css
    - _assets/img
    - _assets/img/posts
    - _assets/img/portfolio-logos
  js_compressor: uglifier
  css_compressor: yui
  cachebust: soft
  gzip: false # use https://github.com/laurilehmijoki/s3_website for gzipping

exclude:
  - Rakefile

prod: true
