auto: true

pygments: true
markdown: redcarpet
permalink: /:categories/:title 

author:
  name: Ted Serbinski

title : Ted Serbinski
description: A blog covering early-stage startup investing written by an entrepreneur & hacker turned VC living in Detroit.

exclude: ['Rakefile', 'README.md', 'aws_s3_redirect']
