auto: true

pygments: true
markdown: redcarpet
permalink: /:categories/:title 

author:
  name: Ted Serbinski

title : Ted Serbinski
description: Startup lessons from an entreprenuer and open source hacker, turned early stage VC at Detroit Venture Partners, helping to rebuild Detroit.

exclude: ['Rakefile', 'README.md', 'aws_s3_redirect']
