auto: true

pygments: true
markdown: redcarpet
permalink: /:categories/:title 

author:
  name: Ted Serbinski

title : Ted Serbinski
description: A blog covering startup lessons from an entreprenuer and open source hacker turned early stage VC living in Detroit.

exclude: ['Rakefile', 'README.md', 'aws_s3_redirect']
